image: registry.gitlab.com/polytechnique-montr-al/inf3995/20213/equipe-100/inf3995-backend/ci:0.0.2

.cache: &pull_cache
  - key:
      files:
        - poetry.lock
    paths:
      - .venv
    policy: pull

.only: &only
  refs:
    - main
    - merge_requests

stages:
  - install
  - test
  - tag_release

install:
  stage: install
  script:
    - poetry config virtualenvs.in-project true
    - poetry install --no-root
  cache:
  - key:
      files:
        - poetry.lock
    paths:
      - .venv
    policy: pull-push
  only: *only

static:
  stage: test
  script:
    - poetry run black . --check
    - poetry run flake8
    - poetry run mypy . --show-error-codes
  cache: *pull_cache
  only: *only
  dependencies:
    - install

tests:
  stage: test
  script:
    - poetry run pytest --cov=backend
    - poetry run coverage xml
  cache: *pull_cache
  only: *only
  dependencies:
    - install
  coverage: '/^TOTAL.+?(\d+\%)$/'
  artifacts:
    reports:
      cobertura: coverage.xml

tag_release:
  stage: tag_release
  script:
    - git remote set-url origin https://root:$SEMANTIC_RELEASE_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
    - git config --global user.name "Alfred Pennyworth"
    - git config --global user.email "alfred.pennyworth@polymtl.ca"
    - poetry run semantic-release publish
  cache: *pull_cache
  only:
    refs:
      - main
  variables:
    GIT_STRATEGY: clone
    GITLAB_CI: "true"
  dependencies:
    - static
    - tests
