FROM python:3.9-slim-bullseye

# Install dependencies
RUN apt-get update && apt-get install curl git -y

# Install Poetry
ENV POETRY_HOME="/opt/poetry"
ENV PATH="$POETRY_HOME/bin:$PATH"
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
