FROM adoptopenjdk/openjdk11

RUN apt-get update && apt-get install -y wget

# Install the generator
RUN mkdir -p /openapitools && \
    wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.3.0/openapi-generator-cli-5.3.0.jar -O /openapitools/openapi-generator-cli.jar
