FROM adoptopenjdk/openjdk11

RUN apt-get update && apt-get install -y wget

# Install the generator
RUN mkdir -p /openapitools && \
    wget https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.3.1-SNAPSHOT/openapi-generator-cli-5.3.1-20211204.171422-36.jar -O /openapitools/openapi-generator-cli.jar
